# Generated by Django 5.0.2 on 2024-02-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy_course_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_item', models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Skill Development', 'Skill Development'), ('Others', 'Others')], max_length=100, null=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=50)),
                ('duration_hour', models.FloatField()),
                ('duration_day', models.IntegerField(blank=True, null=True)),
                ('total_student', models.IntegerField(blank=True, default=1, null=True)),
                ('total_review_person', models.IntegerField(blank=True, default=1, null=True)),
                ('course_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('course_banner', models.ImageField(upload_to='CourseBannerImage')),
                ('demo_class_link_YT', models.CharField(max_length=300)),
                ('course_playlist_link', models.CharField(max_length=200)),
                ('popular_or_not', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True)),
                ('read_more_button', models.CharField(blank=True, max_length=200, null=True)),
                ('join_now_button', models.CharField(blank=True, max_length=200, null=True)),
                ('background_image', models.ImageField(upload_to='carousel_slider')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('subjects', models.CharField(blank=True, max_length=100, null=True)),
                ('messages', models.CharField(max_length=500)),
                ('show_review_home', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expert_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=75)),
                ('instructor_profile_picture', models.ImageField(upload_to='InstructorImage')),
                ('fb_profile_link', models.CharField(max_length=200)),
                ('linkedIn_profile_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_profile_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaQ_list_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(verbose_name=1000)),
                ('course_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.academy_course_item')),
            ],
        ),
    ]
