# Generated by Django 5.0.2 on 2024-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_course_item',
            name='discount_price',
            field=models.CharField(max_length=50),
        ),
    ]
