# Generated by Django 5.0.2 on 2024-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_alter_academy_course_item_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_course_item',
            name='course_price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='academy_course_item',
            name='duration_day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academy_course_item',
            name='duration_hour',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='academy_course_item',
            name='total_review_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academy_course_item',
            name='total_student',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
