# Generated by Django 4.2.5 on 2024-02-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0003_alter_academy_course_item_course_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.academy_course_item')),
            ],
        ),
        migrations.DeleteModel(
            name='FaQ_list_Item',
        ),
    ]
